# Cloudflare Pages配置（服务端渲染模式）
name = "julesgpt"

# 指定构建输出目录
pages_build_output_dir = ".next"

# 构建配置
[build]
command = "npm run build"

# 环境变量配置
[vars]
NODE_VERSION = "20.9.0"

# 使用Node.js兼容性运行时
compatibility_flags = ["nodejs_compat"]

# 环境配置
[env.production]
name = "julesgpt-production"
route = "*julesgpt.com/*"

[env.staging]
name = "julesgpt-staging"
route = "*julesgpt-staging.pages.dev/*" 