# Cloudflare Pages配置
name = "julesgpt"

# 指定构建输出目录
pages_build_output_dir = ".next"

# 使用Node.js兼容性运行时
compatibility_flags = ["nodejs_compat"]

# 生产环境配置
[env.production]
# 生产环境特定变量
[env.production.vars]
NODE_ENV = "production"
NODE_VERSION = "20.9.0"
NPM_FLAGS = "--legacy-peer-deps"

# 预览环境配置
[env.preview]
# 预览环境特定变量
[env.preview.vars]
NODE_ENV = "preview"
NODE_VERSION = "20.9.0"
NPM_FLAGS = "--legacy-peer-deps"