# Cloudflare Pages配置（服务端渲染模式）
name = "julesgpt"

# 构建配置
[build]
command = "npm run build"

[build.environment]
NODE_VERSION = "20.9.0"

# 使用Node.js兼容性运行时
[compatibility_flags]
nodejs_compat = true

# 环境配置
[env.production]
name = "julesgpt-production"
route = "*julesgpt.com/*"

[env.staging]
name = "julesgpt-staging"
route = "*julesgpt-staging.pages.dev/*" 