export interface FAQItem {
  question: string;
  answer: string;
}

export interface Tool {
  id: string;
  name: string;
  iconName: string; // Lucide图标名称
  description: string;
  faqs: FAQItem[];
  inputPlaceholder: string;
  actionButtonText: string;
  apiEndpoint: string;
}

const toolsData: Tool[] = [
  {
    id: "ai-detector",
    name: "AI Content Detector",
    iconName: "Scan",
    description: "Detect content generated by OpenAI, Gemini, and other AI models with high accuracy and detailed analysis.",
    faqs: [
      {
        question: "How does the AI detector work?",
        answer: "Our AI detector uses advanced algorithms to analyze text patterns, linguistic markers, and other characteristics that are typical of AI-generated content. It highlights each sentence and provides a probability score indicating how likely it was created by AI."
      },
      {
        question: "Which AI models can Higgsfieldgpt detect?",
        answer: "Higgsfieldgpt can detect content generated by OpenAI's models (including ChatGPT, GPT-4), Google's Gemini, and other major AI language models with high accuracy."
      },
      {
        question: "How accurate is the detection?",
        answer: "Our detector achieves over 95% accuracy in identifying AI-generated content. However, heavily edited AI text or very short samples may be more challenging to detect accurately."
      }
    ],
    inputPlaceholder: "Paste text here to analyze for AI-generated content or upload a file...",
    actionButtonText: "Detect AI",
    apiEndpoint: "/api/detect"
  },
  {
    id: "plagiarism-checker",
    name: "Plagiarism Checker",
    iconName: "FileSearch",
    description: "Check your text against billions of web pages and academic papers to ensure originality.",
    faqs: [
      {
        question: "How does the plagiarism checker work?",
        answer: "Our plagiarism checker compares your text against a vast database of web content, academic papers, and publications to identify any matching or similar content."
      },
      {
        question: "What types of plagiarism can it detect?",
        answer: "It can detect direct copying, paraphrasing, word switching, and other forms of content reuse from published sources."
      },
      {
        question: "Can I check academic papers for plagiarism?",
        answer: "Yes, our tool is ideal for students and academics to verify the originality of research papers, essays, and dissertations before submission."
      }
    ],
    inputPlaceholder: "Paste your text here or upload a file to check for plagiarism...",
    actionButtonText: "Check Plagiarism",
    apiEndpoint: "/api/plagiarism"
  },
  {
    id: "paraphraser",
    name: "AI Humanizer",
    iconName: "PenTool",
    description: "Transform AI-generated content to sound more human and bypass AI detection tools.",
    faqs: [
      {
        question: "How does the AI Humanizer work?",
        answer: "Our AI Humanizer analyzes text for patterns typical of AI generation, then rewrites the content to introduce more human-like language patterns, idioms, and structural variations while preserving the original meaning."
      },
      {
        question: "Will humanized text pass AI detection?",
        answer: "In most cases, yes. Our humanizer specifically targets the patterns that AI detectors look for, making the text appear more natural and human-written to detection algorithms."
      },
      {
        question: "Does humanizing text affect quality?",
        answer: "No, our tool maintains or even improves the quality of writing by introducing more natural language flow and eliminating common AI writing patterns."
      }
    ],
    inputPlaceholder: "Paste AI-generated text here to make it sound more human...",
    actionButtonText: "Humanize Text",
    apiEndpoint: "/api/humanize"
  },
  {
    id: "batch-analyzer",
    name: "Batch File Analyzer",
    iconName: "Files",
    description: "Upload multiple files simultaneously for AI content detection and receive comprehensive reports.",
    faqs: [
      {
        question: "How many files can I analyze at once?",
        answer: "Free users can analyze up to 3 files simultaneously. Premium users can process up to 20 files in a single batch."
      },
      {
        question: "What file formats are supported?",
        answer: "Currently we support .txt, .docx, and .pdf files for batch analysis. More formats will be added in future updates."
      },
      {
        question: "How are batch results presented?",
        answer: "Results are displayed in a dashboard view with individual scores for each file. You can also download a comprehensive report for all files or view detailed analysis for each file individually."
      }
    ],
    inputPlaceholder: "Drop multiple files here or click to upload...",
    actionButtonText: "Analyze Files",
    apiEndpoint: "/api/batch-analyze"
  },
  {
    id: "grammar-checker",
    name: "Grammar Checker",
    iconName: "CheckSquare",
    description: "Improve your writing with our advanced grammar, spelling, and style checker powered by AI.",
    faqs: [
      {
        question: "What types of errors can the grammar checker detect?",
        answer: "Our grammar checker identifies spelling errors, grammatical mistakes, punctuation issues, word choice problems, sentence structure issues, and style inconsistencies."
      },
      {
        question: "Does it work with multiple languages?",
        answer: "Yes, our grammar checker supports multiple languages including English, Spanish, French, German, Chinese, and more with varying levels of capability."
      },
      {
        question: "How does it differ from built-in word processor checkers?",
        answer: "Unlike basic spell checkers, our AI-powered tool recognizes context-dependent errors, offers style suggestions, and provides explanations for each correction to help improve your writing skills."
      }
    ],
    inputPlaceholder: "Paste text here to check for grammar and spelling errors...",
    actionButtonText: "Check Grammar",
    apiEndpoint: "/api/grammar"
  },
  {
    id: "translator",
    name: "AI Translator",
    iconName: "Globe",
    description: "Translate text between hundreds of languages with high accuracy and natural phrasing.",
    faqs: [
      {
        question: "How many languages are supported?",
        answer: "Our translator supports over 100 languages from around the world, including major languages like English, Chinese, Spanish, Arabic, and less common ones."
      },
      {
        question: "How accurate is the translation?",
        answer: "Our AI-powered translator provides highly accurate translations that maintain the original meaning, context, and tone. It's especially good at handling idioms and cultural nuances."
      },
      {
        question: "Can it translate specialized content?",
        answer: "Yes, our translator performs well with specialized content like technical documents, legal texts, and academic papers, preserving terminology and subject-specific language."
      }
    ],
    inputPlaceholder: "Paste text here to translate...",
    actionButtonText: "Translate",
    apiEndpoint: "/api/translate"
  },
  {
    id: "summarizer",
    name: "Text Summarizer",
    iconName: "FileDigit",
    description: "Create concise, accurate summaries of long texts, articles, or documents instantly.",
    faqs: [
      {
        question: "How does the text summarizer work?",
        answer: "Our AI summarizer analyzes the content to identify key topics, main ideas, and critical details. It then generates a condensed version that maintains the core information while eliminating redundancy."
      },
      {
        question: "Can I adjust the summary length?",
        answer: "Yes, you can specify the desired length of your summary as a percentage of the original text, allowing for very brief summaries or more detailed condensed versions."
      },
      {
        question: "What types of content can I summarize?",
        answer: "You can summarize virtually any text content including articles, research papers, reports, news stories, books, and more. The tool works best with well-structured content."
      }
    ],
    inputPlaceholder: "Paste long text here to generate a summary...",
    actionButtonText: "Summarize",
    apiEndpoint: "/api/summarize"
  },
  {
    id: "content-writer",
    name: "AI Content Writer",
    iconName: "Pencil",
    description: "Generate high-quality, original content for blogs, articles, marketing materials, and more.",
    faqs: [
      {
        question: "What types of content can it create?",
        answer: "Our AI writer can generate blog posts, articles, product descriptions, marketing copy, social media content, email newsletters, and more with customized styles and tones."
      },
      {
        question: "How do I get the best results?",
        answer: "Provide clear guidance about your target audience, desired tone, content type, and key points you want to address. The more specific your instructions, the better the output."
      },
      {
        question: "Is the content original and SEO-friendly?",
        answer: "Yes, our AI generates original content tailored to your specifications. It can incorporate SEO best practices, including proper keyword usage and optimal content structure."
      }
    ],
    inputPlaceholder: "Describe the content you want to generate...",
    actionButtonText: "Generate Content",
    apiEndpoint: "/api/content-writer"
  }
];

export default toolsData; 